name: Release

on:
  push:

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        settings:
          - host: macos-latest
            name: "darwin-x64"
          # - host: windows-latest
          #   name: "win32-ia32"

    name: stable - ${{ matrix.settings.name }} - node@16
    runs-on: ${{ matrix.settings.host }}
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: xltan/build-tools
          path: build-tools

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install build-tools
        run: npm install

      - uses: sinoru/actions-setup-xcode@v2
        with:
          xcode-version: "12.4"

      - name: Init
        run: |
          npx e init release -i release --root=electron --fork xltan/electron --force

      - name: Cache electron-src
        id: cache-electron-src
        uses: actions/cache@v2
        with:
          path: electron
          key: ${{ runner.os }}-${{ hashFiles('package.json') }}-electron

      - uses: actions/checkout@v3
        with:
          repository: xltan/electron
          path: electron/src/electron
          ref: v18.2.3
          fetch-depth: 0

      - name: Apply patches
        working-directory: electron/src/electron
        run: |
          git cherry-pick custom-electron

      # - name: Sync
      #   run: |
      #     npx e sync

      - name: Build
        run: |
          npx e build electron:symbols
